package op_test

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"

	"github.com/sgrankin/wave/internal/codec"
	"github.com/sgrankin/wave/internal/op"
)

// TestEditorOpValidity is the TS→Go conformance guard: it proves every TypeScript
// editor op-builder (web/src/editor/blipdoc.ts) emits ops the SERVER submit-path
// validator (op.Validate) ACCEPTS. The client's permissive compose() tolerates ops
// the validator rejects — the setAnnotationRange un-bold / cross-paragraph-clear bug
// class, masked by the editor's optimistic apply — so a builder can ship a latent
// fatal-NACK defect that no client-side test catches. The corpus is generated by
// `node web/testing/gen-op-validity.ts` (regenerate after a builder change); each case
// is a real builder output applied to a doc it is valid-by-construction for, covering
// happy paths AND the hard edge cases (whole-doc, zero-length, cross-paragraph null
// gap, adjacency to a same-value run, mixed pre-existing values). The test PASSES iff
// op.Validate(doc, op) returns nil for every case.
func TestEditorOpValidity(t *testing.T) {
	const path = "testdata/editor_op_validity.json"
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var cases []struct {
		Builder string `json:"builder"`
		Note    string `json:"note"`
		Doc     string `json:"doc"`
		Op      string `json:"op"`
	}
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(cases) == 0 {
		t.Fatalf("no editor-op-validity cases loaded from %s", path)
	}

	decode := func(h string) (op.DocOp, error) {
		b, err := hex.DecodeString(h)
		if err != nil {
			return op.DocOp{}, err
		}
		return codec.DecodeDocOp(b)
	}

	for _, c := range cases {
		doc, err := decode(c.Doc)
		if err != nil {
			t.Errorf("%s / %s: decode doc: %v", c.Builder, c.Note, err)
			continue
		}
		o, err := decode(c.Op)
		if err != nil {
			t.Errorf("%s / %s: decode op: %v", c.Builder, c.Note, err)
			continue
		}
		if err := op.Validate(doc, o); err != nil {
			t.Errorf("%s / %s: %v", c.Builder, c.Note, err)
		}
	}
}
