package codec_test

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"

	"github.com/sgrankin/wave/internal/codec"
	"github.com/sgrankin/wave/internal/op"
)

// The OT golden vectors in web/src/wave/testdata/fixtures.json are generated by
// cmd/genfixtures (Go) and consumed by the TS port's compose/transform tests — but
// the Go side never read them back. So Go's compose/transform could silently drift
// from the committed fixtures the TS tests still pass against, and the two ports
// would diverge with no failing test. These tests close that: they re-verify Go's
// compose and transform against the SAME committed fixtures, so a Go OT change that
// would invalidate the TS oracle fails here first. (Regenerate the fixtures with
// `go run ./cmd/genfixtures > web/src/wave/testdata/fixtures.json` after an
// intentional change, which updates both sides together.)

const fixturesPath = "../../web/src/wave/testdata/fixtures.json"

type otFixtures struct {
	Compose []struct {
		Note string `json:"note"`
		A    string `json:"a"`
		B    string `json:"b"`
		Out  string `json:"out"`
	} `json:"compose"`
	Transform []struct {
		Note        string `json:"note"`
		Client      string `json:"client"`
		Server      string `json:"server"`
		ClientPrime string `json:"clientPrime"`
		ServerPrime string `json:"serverPrime"`
	} `json:"transform"`
}

func loadOTFixtures(t *testing.T) otFixtures {
	t.Helper()
	data, err := os.ReadFile(fixturesPath)
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	var fx otFixtures
	if err := json.Unmarshal(data, &fx); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}
	return fx
}

func fxDocOp(t *testing.T, h string) op.DocOp {
	t.Helper()
	b, err := hex.DecodeString(h)
	if err != nil {
		t.Fatalf("hex %q: %v", h, err)
	}
	d, err := codec.DecodeDocOp(b)
	if err != nil {
		t.Fatalf("decode docop %q: %v", h, err)
	}
	return d
}

// TestComposeMatchesFixtures verifies Go's Compose against every committed
// compose vector (the cross-port oracle the TS tests also use).
func TestComposeMatchesFixtures(t *testing.T) {
	fx := loadOTFixtures(t)
	if len(fx.Compose) == 0 {
		t.Fatal("no compose fixtures loaded")
	}
	for _, c := range fx.Compose {
		got, err := op.Compose(fxDocOp(t, c.A), fxDocOp(t, c.B))
		if err != nil {
			t.Errorf("%q: compose error: %v", c.Note, err)
			continue
		}
		if !got.Equal(fxDocOp(t, c.Out)) {
			t.Errorf("%q: compose(a, b) does not match the fixture out", c.Note)
		}
	}
}

// TestTransformMatchesFixtures verifies Go's Transform against every committed
// transform vector (both client' and server' sides).
func TestTransformMatchesFixtures(t *testing.T) {
	fx := loadOTFixtures(t)
	if len(fx.Transform) == 0 {
		t.Fatal("no transform fixtures loaded")
	}
	for _, c := range fx.Transform {
		cp, sp, err := op.Transform(fxDocOp(t, c.Client), fxDocOp(t, c.Server))
		if err != nil {
			t.Errorf("%q: transform error: %v", c.Note, err)
			continue
		}
		if !cp.Equal(fxDocOp(t, c.ClientPrime)) {
			t.Errorf("%q: transform clientPrime does not match the fixture", c.Note)
		}
		if !sp.Equal(fxDocOp(t, c.ServerPrime)) {
			t.Errorf("%q: transform serverPrime does not match the fixture", c.Note)
		}
	}
}
